"use client";

import { FormEvent, useCallback, useEffect, useState } from "react";
import { AlertTriangle, Save } from "lucide-react";

interface Registration { _id: string; firstName?: string; lastName?: string; imei: string; policyNumber?: string; packageType?: string; devicePrice?: number; approvedAt?: string; createdAt: string }

export default function CoverageDataPage() {
    const [items, setItems] = useState<Registration[]>([]);
    const [selected, setSelected] = useState<Registration | null>(null);
    const [form, setForm] = useState({ planName: "", packagePrice: "", coverageStartDate: "", coverageEndDate: "" });
    const [error, setError] = useState("");
    const load = useCallback(async () => { const response = await fetch("/api/admin/buybacks/coverage-data", { cache: "no-store" }); const payload = await response.json(); if (response.ok) setItems(payload.registrations || []); else setError(payload.error || "โหลดข้อมูลไม่สำเร็จ"); }, []);
    useEffect(() => { const timer = window.setTimeout(() => void load(), 0); return () => window.clearTimeout(timer); }, [load]);
    const choose = (item: Registration) => { const start = new Date(item.approvedAt || item.createdAt); const end = new Date(start); end.setFullYear(end.getFullYear() + 1); setSelected(item); setForm({ planName: "", packagePrice: "", coverageStartDate: start.toISOString().slice(0, 10), coverageEndDate: end.toISOString().slice(0, 10) }); };
    const save = async (event: FormEvent) => { event.preventDefault(); if (!selected) return; setError(""); const response = await fetch("/api/admin/buybacks/coverage-data", { method: "PUT", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ ...form, registrationId: selected._id, packageType: selected.packageType }) }); const payload = await response.json(); if (response.ok) { setSelected(null); void load(); } else setError(payload.error || "บันทึกไม่สำเร็จ"); };
    return <div className="mx-auto max-w-5xl space-y-6"><div><h1 className="text-2xl font-black text-slate-900">แก้ข้อมูลแพ็กเก่า</h1><p className="text-sm text-slate-500">เฉพาะแพ็กที่ migration ไม่สามารถสร้าง snapshot ได้</p></div>{error && <div className="rounded-xl bg-red-50 p-4 text-red-600">{error}</div>}<div className="grid gap-5 lg:grid-cols-2"><div className="min-w-0 space-y-3">{items.length === 0 ? <div className="rounded-2xl bg-emerald-50 p-8 text-center font-bold text-emerald-600">ข้อมูลแพ็กครบทั้งหมดแล้ว</div> : items.map(item => <button key={item._id} onClick={() => choose(item)} className={`w-full rounded-2xl border bg-white p-4 text-left shadow-sm sm:p-5 ${selected?._id === item._id ? "border-blue-500" : "border-slate-100"}`}><div className="flex items-center gap-2"><AlertTriangle className="shrink-0 text-amber-500" size={17} /><b>{item.firstName} {item.lastName}</b></div><p className="mt-1 break-words text-xs text-slate-400">{item.policyNumber || "ไม่มีเลขแพ็ก"} · {item.imei}</p></button>)}</div>{selected && <form onSubmit={save} className="h-fit min-w-0 space-y-4 rounded-2xl bg-white p-4 shadow-sm sm:p-6"><h2 className="font-black text-slate-800">กำหนด snapshot</h2><label className="block space-y-1"><span className="text-xs font-bold text-slate-500">ชื่อแพ็ก</span><input required value={form.planName} onChange={event => setForm({ ...form, planName: event.target.value })} className="w-full rounded-xl border p-3" /></label><label className="block space-y-1"><span className="text-xs font-bold text-slate-500">ราคาแพ็ก (บาท)</span><input required inputMode="decimal" value={form.packagePrice} onChange={event => setForm({ ...form, packagePrice: event.target.value })} className="w-full rounded-xl border p-3" /></label><div className="grid gap-3 sm:grid-cols-2"><label className="space-y-1"><span className="text-xs font-bold text-slate-500">วันเริ่ม</span><input required type="date" value={form.coverageStartDate} onChange={event => setForm({ ...form, coverageStartDate: event.target.value })} className="w-full rounded-xl border p-3" /></label><label className="space-y-1"><span className="text-xs font-bold text-slate-500">วันสิ้นสุด</span><input required type="date" value={form.coverageEndDate} onChange={event => setForm({ ...form, coverageEndDate: event.target.value })} className="w-full rounded-xl border p-3" /></label></div><button className="flex w-full items-center justify-center gap-2 rounded-xl bg-blue-600 py-3 font-black text-white"><Save size={16} /> บันทึกข้อมูล</button></form>}</div></div>;
}
